### PR TITLE
PHP 5.6 CA file/path

### PR DESCRIPTION
**Pull request by xsist10**
This is added for the new changes to PHP 5.6 (only affects version >= 5.6 but may be backported to PHP 5.5 later) for TLS Peer verification:

"Global CA defaults may be specified via new openssl.cafile and openssl.capath php.ini directives" (https://wiki.php.net/rfc/tls-peer-verification, https://wiki.php.net/rfc/improved-tls-defaults)

Slightly different from a straight php.ini configuration setting though as, if php.ini does not have a setting specified, it defaults to the settings specified in the installed version of openssl.

Tests added as well (and small fixes to other tests).

Be aware that PHP is still in 5.6.0-alpha3 release at the moment so this functionality may change before final release.

### CODE REVIEW

**Comment by enygma** [comment]
@xsist10 is this something that still needs to be merged or does it apply anymore?

**Comment by xsist10** [comment]
Yup, it did end up in PHP 5.6.0 without modification from the RFC spec.

I'm not sure why it's failing the Codacy test. When I click the link it just askes me to sign up and after that it still won't give me any feedback.

**Comment by enygma** [comment]
Hmm, I think the Codacy thing might be messed up...there's only issues listed for complexity, unused code and code style, not unit test failures or anything. I'll try the manual merge.

**Comment by enygma** [comment]
Ah, looks like you might just need to pull the latest master and fix some of the conflicts. I think since this PR is a bit old, the project changed out from underneath it. Mind making that update?

**Comment by denji** [comment]
- https://gist.github.com/denji/f2178089b6625c66bf54

```
$caBundlePaths = array(
    '/etc/pki/tls/certs/ca-bundle.crt',         // Fedora, RHEL, CentOS (ca-certificates package)
    '/etc/ssl/certs/ca-certificates.crt',       // Debian, Ubuntu, Gentoo, Arch Linux (ca-certificates package)
    '/etc/ssl/ca-bundle.pem',                   // SUSE, openSUSE (ca-certificates package)
    '/usr/local/share/certs/ca-root-nss.crt',   // FreeBSD (ca_root_nss_package)
    '/usr/ssl/certs/ca-bundle.crt',             // Cygwin
    '/opt/local/share/curl/curl-ca-bundle.crt', // OS X macports, curl-ca-bundle package
    '/usr/local/share/curl/curl-ca-bundle.crt', // Default cURL CA bunde path (without --with-ca-bundle option)
    '/usr/share/ssl/certs/ca-bundle.crt',       // Really old RedHat?
);
```

**Comment by xsist10** [comment]
Not sure if this pull request is still valid but it's been open for a long time so I'm going to close it. Feel free to re-open if you want to resurrect it.

**Pull request closed without merging**
