### PR TITLE
Updated symfony/console version

### PR DESCRIPTION
**Pull request by wasilak**
As described in issue https://github.com/psecio/iniscan/issues/95

### CODE REVIEW

**Comment by enygma** [comment]
Can you do me a favor on this too, the build errors because of the Composer required PHP version:

```
symfony/console v3.0.2 requires php >=5.5.9 -> your PHP version (5.3.29) does not satisfy that requirement.
```

Mind updating that to 5.5.9 in the `composer.json`.

**Comment by wasilak** [comment]
Sure, I upgraded PHP version also for Travis CI.

**Comment by enygma** [comment]
:+1: awesome, thanks!

**Comment by enygma** [comment]
Merged and tagged in `3.6.4`

**Pull request merged**
